zendesk_domain: yourzendeskdomain
zendesk_user: user@example.com/token
zendesk_token: 123abc456
smtp_user: user@example.com
smtp_password: 123456
email_list: notification-list@example.com
# Kiosk modes:
# 0 = normal mode
# 1 = single user dropoff/return mode: tickets are all assigned to the same user
# 2 = end of year return-only mode
kiosk_mode: 0
# Addresses that receive all EOY device return CSV files
eoy_return_addresses: user1@example.com, user2@example.com
# Show daily loaner:true will add buttons on the start screen for daily device and charger borrowing
show_daily_loaner: true
# Show the button to print a report of daily loaner usage by student
show_loaner_report: true
# Email address that daily borrow/return notifications will be sent to
daily_email_list: daily-notification-list@example.com
email_daily_report: false
print_daily_report: true
# Name & email address for single user mode that all tickets will belong to
single_user_first_name: Example
single_user_last_name: User
single_user_email_address: user@example.com
school_abbreviation: EHS
# Should we ask the user what their home room is?
show_homeroom_page: true
# What name should we use for 'homeroom'?  (e.g. 'homeroom', 'advisory', 'block')
homeroom_label: Home Room
# Should get get homeroom from PowerSchool? If true, overrides data from the homeroom page
homeroom_from_ps: false
# PowerSchool API URL, base URL for your PowerSchool server
ps_api_url: https://school.example.com
# PowerSchool Client Secrets {Client ID:Client Secret}
ps_client_id: 123456
ps_client_secret: abcdef