import sys
import os
import datetime
from typing import Any
import requests
import json
import smtplib
import yaml
import shutil
import subprocess
import uuid
import sqlite3
import base64

from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtCore import QObject, Signal, Slot, Qt, QRunnable, QThread, QThreadPool, QProcessEnvironment, QByteArray
from PySide6 import QtGui
from pathlib import Path
from enum import Enum
from email.message import EmailMessage

from send_to_printer import PrinterService, PrinterError

# KioskMode sets the main operational mode that the determines the main screen (Main.qml)
class KioskMode(Enum):
    normal = 0
    singleUser = 1
    eoyReturnOnly = 2

# ServiceMode is set based on the option a user choosees on the main screen (Main.qml)
class ServiceMode(Enum):
    dropoff = 1
    pickup = 2
    dailyDeviceBorrow = 3
    dailyChargerBorrow = 4
    dailyDeviceReturn = 5
    dailyChargerReturn = 6
    staffDeviceBorrow = 7
    staffDeviceReturn = 8

# UI handles all of the logic for the app and passes data to the QML UI
class UI(QObject):
    majorVersion = 2
    minorVersion = 3
    build = 0

    # Signals are special functions that allow a message to be sent from Python to QML UI
    # Instead of calling like a regular function, we call them as:
    # self.[signal].emit(argument)
    enableDailyLoanersSignal = Signal()
    enableLoanersReportSignal = Signal()
    enableStaffSubBorrowSignal = Signal()
    showStaffSubReturnSignal = Signal()
    showUserSignal = Signal()
    showEmailScreenSignal = Signal()
    startOverSignal = Signal()
    showDescriptionSignal = Signal()
    showDeviceSignal = Signal()
    showPrintSignal = Signal()
    showDropoffSignal = Signal()
    enableNextSignal = Signal()
    showLoanerSignal = Signal()
    showSubmitSignal = Signal()
    showSubmitPickupSignal = Signal()
    showReturnSignal = Signal()
    showPickupSignal = Signal()
    showErrorSignal = Signal(str)
    showErrorPageSignal = Signal()
    showFinishSignal = Signal()
    showEOYReturnSignal = Signal()
    showEOYStartSignal = Signal()
    showDailyLoanerDeviceScreenSignal = Signal()
    showDailyLoanerChargerScreenSignal = Signal()    
    showFinishDailyBorrowSignal = Signal()
    showFinishDailyReturnSignal = Signal()
    showOutstandingLoansSignal = Signal(str)
    showDailyHomeroomPageSignal = Signal()
    setHomeroomLabelSignal = Signal(str)
    
    firstName = ""
    lastName = ""
    studentID = ""
    emailAddress = ""
    description = ""
    serialNumber = ""
    loanerSerialNumber = ""
    serviceMode = ServiceMode.dropoff
    schoolLogo = ""
    errorMessage = ""
    homeroom = ""
    config = {}
    powerschoolAuthorizationToken = ""

    printerService = PrinterService()

    def loadConfig(self) -> None:
        path = os.path.dirname(os.path.abspath(__file__))
        # Check for a config-devel.yml file for development
        if os.path.exists(os.path.join(path,'config-devel.yml')):
            print('Using config-devel.yml')
            configFile = os.path.join(path,'config-devel.yml')
        # Check if config.yml exists, if not, copy from config-example.yml to config.yml and open file
        elif os.path.exists(os.path.join(path,'config.yml')) == False:
            print('Config file does not exist. Copying from config-example.yml')
            shutil.copy(os.path.join(path,'config-example.yml'), os.path.join(path,'config.yml'))
            configFile = os.path.join(path,'config.yml')
            print("Opening config file for editing")
            if sys.platform.startswith('darwin'):
                subprocess.call(('open', configFile))
            elif os.name == 'nt':   # For Windows
                os.startfile(configFile)
            elif os.name == 'posix':   # For Linux, Unix, etc.
                subprocess.call(('xdg-open', configFile))
            sys.exit(0)
        # Otherwise, use the standard config.yml
        else:
            configFile = os.path.join(path,'config.yml')
        self.config = yaml.safe_load(open(configFile))
        print("devicekiosk.py daily loaner status: " + str(self.config["show_daily_loaner"]))

    # Slots are special functions that allow a message to be sent from QML UI to Python

    # Simple test to see if the QML UI is communicating with Python
    @Slot()
    def test(self) -> None:
        print("test")

    # Errors generated by Python are stored in errorMessage
    # This function allows the QML UI to display the error message
    @Slot()
    def checkForErrors(self) -> None:
        self.showErrorSignal.emit(self.errorMessage)
    
    # Set the kiosk mode from the QML UI
    @Slot(result=int)
    def getKioskMode(self) -> int:
        return self.config["kiosk_mode"]
    
    # Set the service mode from the QML UI
    @Slot(result=int)
    def getServiceMode(self) -> int:
        return self.serviceMode.value

    # For single user mode (all tickets go in from the same user), load the username from the config file
    @Slot(result=str)
    def getSingleUserName(self) -> str:
        return self.config["single_user_first_name"] + " " + self.config["single_user_last_name"]
    
    # For end of year mode, load the email address from the config file that will receive the return files
    @Slot(result=str)
    def getEOYEmailAddresses(self) -> str:
        return self.config["eoy_return_addresses"]

    # Reset the kiosk to the main screen
    @Slot()
    def startOver(self) -> None:
        self.firstName = ""
        self.lastName = ""
        self.studentID = ""
        self.emailAddress = ""
        self.description = ""
        self.serialNumber = ""
        self.loanerSerialNumber = ""
        self.serviceMode = ServiceMode.dropoff
        self.errorMessage = ""
        self.startOverSignal.emit()

    # Show or hide the Daily Loaner buttons in Main.qml based on the config file
    @Slot()
    def showHideDailyLoaners(self) -> None:
        if (self.config["show_daily_loaner"] == True):
            print("showing daily loaners")
            self.enableDailyLoanersSignal.emit()
        else:
            print("keeping daily loaners hidden")
        
        if (self.config["show_loaner_report"] == True):
            print("showing loaner report")
            self.enableLoanersReportSignal.emit()
        else:
            print("keeping loaner report hidden")
        
        if (self.config["show_staff_sub_borrow"] == True):
            print("showing staff sub borrow")
            self.enableStaffSubBorrowSignal.emit()
        else:
            print("keeping staff sub borrow hidden")

    # Receive data from User.qml and direct set the correct next screen based on the service mode
    @Slot(list)
    def submitUser(self, userInfo) -> None:
        print(userInfo)
        self.firstName = userInfo[0]        
        self.lastName = userInfo[1]        
        self.studentID = userInfo[2]
        
        # Strip spaces. Some users were putting spaces after their first and last name
        self.firstName = self.firstName.replace(" ", "")
        self.lastName = self.lastName.replace(" ", "")
        self.studentID = self.studentID.replace(" ", "")
        if(self.serviceMode == ServiceMode.staffDeviceBorrow):
            self.emailAddress = userInfo[3].replace(" ", "")
        else:
            self.emailAddress = self.firstName + self.lastName + self.studentID + "@tolland.k12.ct.us"
        print("User email is: " + self.emailAddress)
        print("Service mode is: " + str(self.serviceMode))
        if (self.serviceMode == ServiceMode.dropoff):
            self.showDescriptionSignal.emit()
        elif (self.serviceMode == ServiceMode.dailyDeviceBorrow
              or self.serviceMode == ServiceMode.staffDeviceBorrow):
            print("Python daily device mode")
            self.showDailyLoanerDeviceScreenSignal.emit()
        elif (self.serviceMode == ServiceMode.dailyChargerBorrow):
            print("Python daily charger mode")
            self.showDailyLoanerChargerScreenSignal.emit()
        else:
            self.showReturnSignal.emit()
        
    # Receive the serial number from Device.qml or Pickup.qml and set the screen in QML based on the service mode
    @Slot(str)
    def submitSerial(self, serial) -> None:
        self.serialNumber = serial
        self.serialNumber = self.serialNumber.replace(" ", "")      
        if (self.serviceMode == ServiceMode.dropoff):
            self.showPrintSignal.emit()
        else:
            self.showSubmitPickupSignal.emit()

    # Receive the service mode from Start.qml and set the service mode in Python
    # Start.qml is the default screen loaded in the Main.qml StackView
    @Slot(int)
    def start(self, mode) -> None:
        self.serviceMode = ServiceMode(mode)
        print("Service mode: ")
        print(self.serviceMode)
        
        if (self.serviceMode == ServiceMode.dailyDeviceReturn):
            self.showReturnSignal.emit()
        elif (self.serviceMode == ServiceMode.dailyChargerReturn):
            self.showReturnSignal.emit()
        elif(self.serviceMode == ServiceMode.staffDeviceReturn):
            self.showReturnSignal.emit()
        else:
            self.showUserSignal.emit()

        # Rocky Linux has Python 3.9, 3.10 required for switch/match statements
        # match self.serviceMode:
        #     case ServiceMode.dailyDeviceReturn:
        #         self.showReturnSignal.emit()
        #     case ServiceMode.dailyChargerReturn:
        #         self.showReturnSignal.emit()
        #     case _:
        #         self.showUserSignal.emit()


    # Receive the problem description from Description.qml and set the screen in QML based on the service mode
    @Slot(str)
    def submitDescription(self, description) -> None:
        self.description = description
        print("Problem Descritpion:")
        print(self.description)
        self.showDeviceSignal.emit()

    # Load the school logo ASCII art logo from schoollogo.txt
    def loadSchoolLogo(self) -> None:
        path = os.path.dirname(os.path.abspath(__file__))
        logo = os.path.join(path,'images','schoollogo.txt')
        with open(logo, 'r') as file:
            self.schoolLogo = file.read()
    
    # Print the ticket to the default printer
    @Slot()
    def printTicket(self) -> None:
        date = datetime.datetime.now()
        ticket = self.schoolLogo + "\n\n\nEmail: " + self.emailAddress + "\nService Tag: " + self.serialNumber + "\nDate: " + date.strftime("%x") + "\nDescription: " + self.description
        ticket += "\n\n\n----- IT Use -----\n\n\nTicket Number: \n\n\n\n\n\nDate Completed:\n\n\n\n"

        if (self.config["schedule_from_ps"] == True):
            ticket += self.getStudentSchedule()

        ticket += "\n\n\nAdditional Information:"
        print(ticket)

        try:
            self.printerService.print_job(ticket)
        except PrinterError as exc:
            self.setError("Unable to print ticket: " + str(exc))
            print(self.errorMessage)
        finally:
            self.enableNextSignal.emit()

    def getStudentSchedule(self) -> str:
        schedule = "---- Student Schedule -----\n"
        try:
            self.authenticateWithPowerSchool()
            url = self.config["ps_api_url"] + "/ws/schema/query/us.ct.k12.tolland.devicekiosk.students.get_schedule"
            payload = {"studentNumber": self.studentID, "terms": self.config["schedule_terms"]}
            print(payload)
            headers = {
                "Content-Type": "application/json",
                "Accept": "application/json",
                "Authorization": "Bearer " + self.powerschoolAuthorizationToken
            }
            response = requests.request("POST", url, json=payload, headers=headers)
            data = response.json()
            for item in data["record"]:
                period = item["external_expression"]
                lastName = item["last_name"]
                room = item["room"]
                line = period + " - " + lastName + " - " + room + "\n"
                schedule += line
        except Exception as e:
            print("An error occurred:", str(e))

        # print(data)
        # schedule += str(data)
        return schedule
        
    # Submit the QML form from Submit.qml and move user to the next screen
    @Slot()
    def submitPrint(self) -> None:
        self.showDropoffSignal.emit()

    # Submit the QML form from Dropoff.qml and move user to the next screen
    @Slot()
    def submitDropOff(self) -> None:
        self.showLoanerSignal.emit()

    # Receive loaner information from Loaner.qml, DailyLoanerDevice.qml, or DailyLoanerCharger.qml
    # Move user to the next screen based on the service mode
    @Slot(str)
    def submitLoaner(self, serial) -> None:
        self.loanerSerialNumber = serial
        # Remove superflous spaces
        self.loanerSerialNumber = self.loanerSerialNumber.replace(" ", "")
        if (self.serviceMode == ServiceMode.dailyDeviceBorrow):
            # self.sendDailyEmail()        
            if (self.config["show_homeroom_page"]):
                self.showDailyHomeroomPageSignal.emit()
            else:
                self.addLoanerToDB("Laptop")
                self.showFinishDailyBorrowSignal.emit()
        elif (self.serviceMode == ServiceMode.dailyChargerBorrow):
            # self.sendDailyEmail()            
            if (self.config["show_homeroom_page"]):
                self.showDailyHomeroomPageSignal.emit()
            else:
                self.addLoanerToDB("Charger")
                self.showFinishDailyBorrowSignal.emit()
        elif (self.serviceMode == ServiceMode.staffDeviceBorrow):
            self.addLoanerToDB("Laptop")
            self.showFinishDailyBorrowSignal.emit()
        else:
            self.showSubmitSignal.emit()

    # Receive the homeroom from Homeroom.qml and set the screen in QML
    @Slot(str)
    def submitHomeroom(self, homeroom) -> None:
        self.homeroom = homeroom
        if (self.serviceMode == ServiceMode.dailyDeviceBorrow):
             self.addLoanerToDB("Laptop")
        elif (self.serviceMode == ServiceMode.dailyChargerBorrow):
            self.addLoanerToDB("Charger")
        self.showFinishDailyBorrowSignal.emit()

    # On startup, we'll create the daily loaner table in daily.db if it doesn't exist
    # TODO: Add checks for the table and columns and update as necessary for new versions
    # For 2.3.0
    # alter table DAILY add Is_Staff integer default 0 not null;
    def createDailyTableIfNotExists(self) -> None:
        print("Creating daily table if it doesn't exist")
        query = """ CREATE TABLE IF NOT EXISTS DAILY(
                    Email TEXT NOT NULL,
                    First_Name TEXT NOT NULL,
                    Last_Name TEXT NOT NULL,
                    Date_Borrowed TEXT NOT NULL,
                    Date_Returned TEXT,
                    Serial TEXT NOT NULL,
                    Device TEXT NOT NULL,
                    Homeroom TEXT,
                    Is_Staff INTEGER DEFAULT 0 NOT NULL
                    ); """
        sqliteConnection = None
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
            cursor.execute(query)
            cursor.close()
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error) 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')
    
    # Make any necessary database table updates
    def updateDatabaseTables(self) -> None:
        print("Updating database tables")
        self.addIsStaffColumn()

    def addIsStaffColumn(self) -> None:
        print("Updating database tables - Adding Is_Staff column to DAILY if necessary")
        query = """SELECT COUNT(*) AS CNTREC FROM pragma_table_info('DAILY') WHERE name='Is_Staff';"""
        columnExists = False
        sqliteConnection = None
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
            result = cursor.execute(query).fetchall()
            if (result[0][0] > 0):
                columnExists = True
            cursor.execute(query)
            cursor.close()
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error) 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')

        # Fetch and output result
        if not columnExists:
            print("Adding Is_Staff column to DAILY")
            query = """ALTER TABLE DAILY ADD Is_Staff INTEGER DEFAULT 0 NOT NULL;"""
            try:   
                # Connect to DB and create a cursor
                path = os.path.dirname(os.path.abspath(__file__))
                db = os.path.join(path,'daily.db')
                sqliteConnection = sqlite3.connect(db)
                cursor = sqliteConnection.cursor()
                cursor.execute(query)
                cursor.close()
            # Handle errors
            except sqlite3.Error as error:
                print('Error occurred - ', error)
            # Close DB Connection irrespective of success
            # or failure
            finally:
                if sqliteConnection:
                    sqliteConnection.close()
                    print('SQLite Connection closed')
        else:
            print("Is_Staff column already exists")


    # Add a daily loaner dervice to the daily.db database
    def addLoanerToDB(self, device) -> None:
        sqliteConnection = None
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
            isStaff = False
            if (self.serviceMode == ServiceMode.staffDeviceBorrow):
                isStaff = True
                    
            # Write a query and execute it with cursor
            query = "INSERT INTO DAILY (Email, First_Name, Last_Name, Date_Borrowed, Serial, Device, Homeroom, Is_Staff) VALUES (?, ?, ?, DATE('now'), ?, ?, ?, ?)"
            args = (self.emailAddress.lower(), self.firstName, self.lastName, self.loanerSerialNumber.lower(), device, self.homeroom, isStaff)
            cursor.execute(query, args)
            sqliteConnection.commit()
        
            # Fetch and output result
            # result = cursor.execute(query)
        
            # Close the cursor
            cursor.close()
        
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error)
 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')

    # Send email notifications for daily device borrows and returns
    # This functionality is not currently used
    def sendDailyEmail(self) -> None:
        msg = EmailMessage() 
        if (self.serviceMode == ServiceMode.dailyDeviceBorrow):
            msg['Subject'] = f'Daily loaner device borrowed by: ' + self.firstName + ' ' + self.lastName
            body = self.firstName + " " + self.lastName + " has borrowed a daily loaner device.\nStudent Number: " + self.studentID + "\nLoaner Device Serial Number: " + self.loanerSerialNumber
            msg.set_content(body)
        elif (self.serviceMode == ServiceMode.dailyDeviceReturn):
            msg['Subject'] = f'Daily loaner device returned by: ' + self.firstName + ' ' + self.lastName
            body = self.firstName + " " + self.lastName + " has returned a daily loaner device.\nStudent Number: " + self.studentID + "\nLoaner Device Serial Number: " + self.loanerSerialNumber
            msg.set_content(body)
        elif (self.serviceMode == ServiceMode.dailyChargerBorrow):
            msg['Subject'] = f'Daily loaner charger borrowed by: ' + self.firstName + ' ' + self.lastName
            body = self.firstName + " " + self.lastName + " has borrowed a daily loaner charger.\nStudent Number: " + self.studentID + "\nLoaner Charger Serial Number: " + self.loanerSerialNumber
            msg.set_content(body)
        elif (self.serviceMode == ServiceMode.dailyChargerReturn):
            msg['Subject'] = f'Daily loaner charger returned by: ' + self.firstName + ' ' + self.lastName
            body = self.firstName + " " + self.lastName + " has returned a daily loaner charger.\nStudent Number: " + self.studentID + "\nLoaner Charger Serial Number: " + self.loanerSerialNumber
            msg.set_content(body)
        msg['From'] = self.config["smtp_user"]
        msg['To'] = self.config["daily_email_list"]

        # Send the message via Gmail SMTP server
        s = smtplib.SMTP("smtp.gmail.com", 587)
        s.ehlo()
        s.starttls()
        s.login(self.config["smtp_user"], self.config["smtp_password"])
        try:
            s.send_message(msg)
        except smtplib.SMTPException as ex:
            self.setError("Error sending email: " + str(ex))
        s.close()
    
    # Receive the returned device serial number from Return.qml and set the screen in QML based on the service mode
    @Slot(str)
    def submitReturn(self, serial) -> None:
        self.loanerSerialNumber = serial
        # Remove superflous spaces
        self.loanerSerialNumber = self.loanerSerialNumber.replace(" ", "")
        if (self.serviceMode == ServiceMode.pickup):
            self.showPickupSignal.emit()
        else:
            self.returnDailyLoaner()

    # Process the daily loaner return from DailyLoanerDevice.qml or DailyLoanerCharger.qml
    def returnDailyLoaner(self) -> None:
        print("python: returning daily loaner")
        # self.sendDailyEmail()
        self.returnLoanerInDB()
        self.showFinishDailyReturnSignal.emit()

    # Update the daily.db database to mark a daily loaner device as returned
    def returnLoanerInDB(self) -> None:
        print("updating daily db for loaner device " + self.loanerSerialNumber.lower())
        sqliteConnection = None
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
                    
            # Write a query and execute it with cursor
            query = "UPDATE DAILY SET Date_Returned = DATE('now') WHERE Serial = ?"
            args = [self.loanerSerialNumber.lower()]
            cursor.execute(query, args)
            sqliteConnection.commit()
        
            # Fetch and output result
            # result = cursor.execute(query)
        
            # Close the cursor
            cursor.close()
        
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error)
 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')

    # Submit the QML form from Submit.qml
    @Slot()
    def submitTicketPage(self) -> None:
        self.showFinishSignal.emit()

    # Submit the ticket to ZenDesk
    @Slot()
    def submitTicket(self) -> None:
        print("submitting ticket")
        self.postToZenDesk()
        if (not str(self.errorMessage) == ""):
            return
        self.sendEmail()
        if (not str(self.errorMessage) == ""):
            return
        self.enableNextSignal.emit()
    
    # Process a repaired device pickup from Pickup.qml
    @Slot()
    def processPickup(self) -> None:
        self.sendEmail()
        self.enableNextSignal.emit()

    # Get the name for 'homeroom'
    @Slot()
    def getAndSetHomeroomName(self) -> None:
        self.setHomeroomLabelSignal.emit(self.config["homeroom_label"])
    
    # Process an end of year return from EOYReturn.qml
    @Slot(list)
    def submitEOYReturn(self, returnInfo) -> None:
        returnSerial = returnInfo[0]
        chargerReturned = returnInfo[1]

        print("end of year submitted")
        self.addToReturnFile(returnSerial, chargerReturned)
        self.showEOYReturnSignal.emit()

    # Completes the EOY return process
    @Slot(str)
    def submitEOYFinish(self, returnEmail) -> None:
        self.emailEOYReturnFiles(returnEmail)
        self.archiveReturns()
        self.showEOYStartSignal.emit()

    # Send the daily loaner/return report
    # Report will be sent via email and/or printed to the default printer based on the config file
    @Slot()
    def dailyReport(self) -> None:
        print("Creating daily report")

        if (self.config["homeroom_from_ps"] == True):
            self.authenticateWithPowerSchool()
        
        body = "Unreturned devices\n"
        sqliteConnection = None
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
                    
            # Write a query and execute it with cursor
            query = "SELECT * FROM DAILY WHERE Date_Returned IS NULL ORDER BY Is_Staff ASC, Last_Name ASC"
            cursor.execute(query)
        
            # Fetch and output result
            result = cursor.execute(query).fetchall()
            for row in result:
                # print(row[0])
                body += row[1] + " " + row[2] + ": " + row[6] + " #: " + row[5] + " Borrowed: " + row[3]
                # If the homeroom is set to be pulled from PowerSchool, add the homeroom to the report
                if (row[8] == True):
                    body += " (Staff)"
                elif (self.config["homeroom_from_ps"] == True):
                    studentNumber = self.getStudentNumberFromEmailAddress(row[0])
                    homeroom = self.getHomeRoomFromPowerSchool(studentNumber)
                    body += " Home Room: " + homeroom
                # Otherwise, if this kiosk shows the Homeroom page, add the homeroom to the report
                elif (self.config["show_homeroom_page"] == True):
                    body += " " + self.config["homeroom_label"] + ": " + str(row[7])
                body += "\n"
        
            # Close the cursor
            cursor.close()
        
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error)
 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')
        
        print(body)
        if (self.config["email_daily_report"] == True):
            self.emailDailyReport(body)

        if (self.config["print_daily_report"] == True):
            try:
                self.printerService.print_job(body)
            except PrinterError as exc:
                print("Unable to print daily report: " + str(exc))

    def getStudentNumberFromEmailAddress(self, emailAddress) -> str:
        print("Getting student number from email address")
        # Get the student number from the email address
        # The email address is in the format FirstLastStudentNumber@tolland.k12.ct.us
        # We'll remove the @tolland.k12.ct.us
        emailParts = emailAddress.split("@") 
        user = emailParts[0]
        # The student number is the last 5 characters of the email address
        if (len(user) < 6):
            print("ERROR: getStudentNumberFromEmailAddress: impossible username and student number, using 00000")
            return "00000"
        studentNumber = user[-5:]
        print("Student number: " + studentNumber)
        return studentNumber
    
    def authenticateWithPowerSchool(self) -> None:
        print("Authenticating with PowerSchool")

        data = self.config["ps_client_id"] + ":" + self.config["ps_client_secret"]
        base64Credentials = base64.b64encode(data.encode('utf-8')).decode('utf-8')

        url = self.config["ps_api_url"] + "/oauth/access_token/"

        print(url)

        payload = "grant_type=client_credentials"
        headers = {
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Authorization": "Basic " + base64Credentials
        }

        response = requests.request("POST", url, data=payload, headers=headers)
        data = response.json()

        # print(data["access_token"])
        self.powerschoolAuthorizationToken = data["access_token"]
    
    def getHomeRoomFromPowerSchool(self, studentID) -> str:
        print("Getting homeroom from PowerSchool")
        url = self.config["ps_api_url"] + "/ws/schema/query/us.ct.k12.tolland.devicekiosk.students.get_home_room"

        payload = {"studentNumber": studentID}
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": "Bearer " + self.powerschoolAuthorizationToken
        }

        response = requests.request("POST", url, json=payload, headers=headers)
        data = response.json()
        # PowerSchool response will look like this: {"record":[{"home_room":"Last - First - Room"}],"@extensions":""}
        if ("record" not in data):
            # If no key "record"
            return "room not found"

        home_room = data["record"][0]["home_room"]
        print(home_room)
        return home_room

    # Check the daily loaner database for outstanding loans
    # If there are outstanding loans, display on the daily loaner screen (DailyLoanerDevice.qml or DailyLoanerCharger.qml)
    @Slot()
    def checkForOustandingLoans(self) -> None:
        print("Checking for outstanding loans")

        loanedDevices = ""

        deviceType = ""
        if (self.serviceMode == ServiceMode.dailyDeviceBorrow):
            deviceType = "Laptop"
        elif (self.serviceMode == ServiceMode.dailyChargerBorrow):
            deviceType = "Charger"
        
        print("Email adddress: " + self.emailAddress.lower())
        print("Device type: " + deviceType)
        sqliteConnection = None
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
                    
            # Write a query and execute it with cursor
            query = "SELECT Serial FROM DAILY WHERE Date_Returned IS NULL AND Email = ? AND Device = ?"
            args = (self.emailAddress.lower(), deviceType)
            print(args)
            #cursor.execute(query, args)
        
            # Fetch and output result
            result = cursor.execute(query, args).fetchall()
            print(result)
            if (len(result) > 0):
                for entry in result:
                    print(entry[0])
                    loanedDevices += entry[0] + " "
                self.showOutstandingLoansSignal.emit(loanedDevices)
                    
            # Close the cursor
            cursor.close()
        
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error)
 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')
    
    @Slot()
    def generateBorrowReport(self) -> None:
        currentSchoolYear = self.thisSchoolYear()
        reportAsOf = "8/1/" + currentSchoolYear
        # print("Generating borrow report since " + currentSchoolYear + "-08-01")
        body = "Borrowed Report since " + reportAsOf + "\n"
        body += "--- Devices ---\n"
        body += self.generateBorrowReportFromSQL(currentSchoolYear, "Laptop")
        body += "\n--- Chargers ---\n"
        body += self.generateBorrowReportFromSQL(currentSchoolYear, "Charger")
        print(body)
        self.printBorrowReport(body)

    def generateBorrowReportFromSQL(self, currentSchoolYear, deviceType) -> str:
        sqliteConnection = None
        report = ""
        try:   
            # Connect to DB and create a cursor
            path = os.path.dirname(os.path.abspath(__file__))
            db = os.path.join(path,'daily.db')
            sqliteConnection = sqlite3.connect(db)
            cursor = sqliteConnection.cursor()
                    
            # Write a query and execute it with cursor
            query = """SELECT Last_Name, First_Name, COUNT(*) AS count, IS_STAFF FROM DAILY WHERE Device = ? AND
                date_borrowed BETWEEN ? AND 'now'
                GROUP BY Last_Name, First_Name
                ORDER BY IS_Staff ASC, count DESC, Last_Name ASC;"""
            args = (deviceType, currentSchoolYear + "-08-01")
            
            
        
            # Fetch and output result
            result = cursor.execute(query, args).fetchall()
            for row in result:
                # report += row[0] + ", " + row[1] + ": " + str(row[2]) + "\n"
                last_name = row[0] if row[0] is not None else ""
                first_name = row[1] if row[1] is not None else ""
                count = str(row[2]) if row[2] is not None else "0"
                report += last_name + ", " + first_name + ": " + count
                if row[3] == True:
                    report += " (Staff)"
                report += "\n"
                        
            # Close the cursor
            cursor.close()

            return report
        
        # Handle errors
        except sqlite3.Error as error:
            print('Error occurred - ', error)
 
        # Close DB Connection irrespective of success
        # or failure
        finally:        
            if sqliteConnection:
                sqliteConnection.close()
                print('SQLite Connection closed')
        return report
    
    def printBorrowReport(self, report) -> None:
        try:
            self.printerService.print_job(report)
        except PrinterError as exc:
            print("Unable to print borrow report: " + str(exc))
    
    def thisSchoolYear(self) -> str:
        today = datetime.date.today()
        if today.month < 8:
            return str(today.year - 1)
        else:
            return str(today.year)

    # Email the daily loaner report
    def emailDailyReport(self, body) -> None:
        msg = EmailMessage()
        msg['Subject'] = 'Daily Loaner Report'
        msg.set_content(body)
        msg['From'] = self.config["smtp_user"]
        msg['To'] = self.config["daily_email_list"]

        # Send the message via Gmail SMTP server
        s = smtplib.SMTP("smtp.gmail.com", 587)
        s.ehlo()
        s.starttls()
        s.login(self.config["smtp_user"], self.config["smtp_password"])
        try:
            s.send_message(msg)
        except smtplib.SMTPException as ex:
            self.setError("Error sending email: " + str(ex))
        s.close()
        
    # Post the ticket to ZenDesk
    def postToZenDesk(self) -> None:
        self.errorMessage = ""
        data = self.createZenDeskTicketBody()
        # Encode the data to create a JSON payload
        print(data)
        payload = json.dumps(data)
        # Set the request parameters
        url = "https://" + self.config["zendesk_domain"] + ".zendesk.com/api/v2/tickets.json"
        user = self.config["zendesk_user"]
        pwd = self.config["zendesk_token"]
        headers = {'content-type': 'application/json'}
        # Do the HTTP post request
        response = requests.post(url, data=payload, auth=(user, pwd), headers=headers)
        # Check for HTTP codes other than 201 (Created)
        if response.status_code != 201:
            self.setError("Failed to create ticket: " + str(response.status_code) + " - " + response.text)  
            self.showErrorSignal.emit('Error: ' + str(response.status_code))
            self.showErrorPageSignal.emit()
            return
        # Report success
        print('Successfully created the ticket.')

    # Create the JSON payload for the ZenDesk ticket
    def createZenDeskTicketBody(self) -> dict[str, Any]:
        # New ticket info
        subject = self.firstName + " " + self.lastName + " Student Device Issue"
        body = self.description + "\nLoaner ID: " + self.loanerSerialNumber
        # Package the data in a dictionary matching the expected JSON
        # "custom_fields": [{"id": 1500007314361, "value": "student_device"}]
        data: dict[str, Any] = {}
        # Regular mode
        if self.config["kiosk_mode"] == 0:
            data = {'ticket': {'subject': subject, 'comment': {'body': body},
                               'requester': {'name': self.firstName + " " + self.lastName, 'email': self.emailAddress},
                               'custom_fields': [{'id': 1500007314361, 'value': 'student_device'},
                                                 {'id': 1500007314401, 'value': self.config["school_abbreviation"]},
                                                 {'id': 1900003862405, 'value': self.serialNumber}]}}
        # Single user mode
        elif self.config["kiosk_mode"] == 1:
            data = {'ticket': {'subject': subject, 'comment': {'body': body},
                               'requester': {'name': self.config["single_user_first_name"] + " " + self.config["single_user_last_name"], 'email': self.config["single_user_email_address"]},
                               'custom_fields': [{'id': 1500007314361, 'value': 'student_device'},
                                                 {'id': 1500007314401, 'value': self.config["school_abbreviation"]},
                                                 {'id': 1900003862405, 'value': self.serialNumber}]}}
        return data
        
    # Send the email notification of a device dropoff or pickup to the users in the config file
    def sendEmail(self) -> None:
        msg = EmailMessage()        
        # me == the sender's email address
        # you == the recipient's email address
        if (self.serviceMode == ServiceMode.dropoff):
            msg['Subject'] = f'Student Device Drop Off: ' + self.firstName + ' ' + self.lastName
            body = self.firstName + " " + self.lastName + " has dropped off a laptop for repair.\nStudent Number: " + self.studentID + "\nDropped off student device serial number: " + self.serialNumber + "\nLoaner Serial Number: " + self.loanerSerialNumber
            msg.set_content(body)
        else:
            msg['Subject'] = f'Student Device Pick Up: ' + self.firstName + ' ' + self.lastName
            body = self.firstName + " " + self.lastName + " has picked up a repaired laptop.\nStudent Number: " + self.studentID + "\nReturned loaner serial number: " + self.loanerSerialNumber + "\nPicked up student device serial number: " + self.serialNumber
            msg.set_content(body)
        msg['From'] = self.config["smtp_user"]
        msg['To'] = self.config["email_list"]

        # Send the message via Gmail SMTP server
        s = smtplib.SMTP("smtp.gmail.com", 587)
        s.ehlo()
        s.starttls()
        s.login(self.config["smtp_user"], self.config["smtp_password"])
        try:
            s.send_message(msg)
        except smtplib.SMTPException as ex:
            self.setError("Error sending email: " + str(ex))
        s.close()

    # Email the end of year return files to the email address in the config file
    def emailEOYReturnFiles(self, returnAddress) -> None:
        msg = EmailMessage()
        msg['Subject'] = 'EOY Return Files'
        body = "EOY Return Files"
        msg.set_content(body)
        attachmentFolder = os.path.dirname(os.path.abspath(__file__))
        # files = 
        for file in os.listdir(attachmentFolder):
            if file.endswith(".csv"):
                with open(os.path.join(attachmentFolder, file), 'rb') as content_file:
                    print(file)
                    content = content_file.read()
                    msg.add_attachment(content, maintype='application', subtype='txt', filename=str(file))
        # email.add_attachment(content, maintype='application', subtype='pdf', filename='example.pdf')
        msg['From'] = self.config["smtp_user"]
        msg['To'] = self.config["eoy_return_addresses"] + ", " + returnAddress
        # Send the message via Gmail SMTP server
        s = smtplib.SMTP("smtp.gmail.com", 587)
        s.ehlo()
        s.starttls()
        s.login(self.config["smtp_user"], self.config["smtp_password"])
        try:
            s.send_message(msg)
        except smtplib.SMTPException as ex:
            self.setError("Error sending email: " + str(ex))
            print("Email error " + str(ex))
        s.close()

    # Add a device to the end of year return file
    def addToReturnFile(self, serial, returnedCharger) -> None:
        print("Adding " + serial + " to return file, with charger: " + str(returnedCharger))
        filename = "eoy-returns-" + str(datetime.date.today()) + ".csv"
        returnsFile = os.path.join(os.path.dirname(os.path.abspath(__file__)),filename)
        if not os.path.exists(returnsFile):
            with open(returnsFile, 'a') as f:
                f.writelines("Serial, Charger\n")
                f.writelines(serial + "," + str(returnedCharger) + "\n")
                f.close()
        else: 
            # Populate version.txt with the newly installed build
            with open(returnsFile, 'a') as f:
                f.writelines(serial + "," + str(returnedCharger) + "\n")
                f.close()

    # Archive the end of year return files
    # Files are archived in a folder named return-archive with a unique ID
    # This provides an on-kiosk backup of the return files in case the email fails
    def archiveReturns(self) -> None:
        workingDir = os.path.dirname(os.path.abspath(__file__))
        archiveDir = os.path.join(workingDir, "return-archive", str(uuid.uuid4()))
        if not os.path.exists(archiveDir):
            os.makedirs(archiveDir)
        for file in os.listdir(workingDir):
            if file.endswith(".csv"):
                shutil.move(os.path.join(workingDir, file), archiveDir)
    
    def setError(self, error) -> None:
        self.errorMessage = str(error)

# Main function
# This sets up the QML UI  with Main.qml and starts the app
def main():
    app = QGuiApplication(sys.argv)    
    # Instatitate objects
    ui = UI()
    ui.loadConfig()
    ui.loadSchoolLogo()
    ui.createDailyTableIfNotExists()
    ui.updateDatabaseTables()
    
    engine = QQmlApplicationEngine()
    # Bind objects to the QML
    engine.rootContext().setContextProperty("ui",ui)
    engine.quit.connect(app.quit)    
    path = os.path.dirname(os.path.abspath(__file__))
    qml = os.path.join(path,'qml','Main.qml')
    
    icon = os.path.join(path, 'icon', 'devicekiosk.ico')
    app.setWindowIcon(QtGui.QIcon(icon))
    
    engine.load(qml)
    sys.exit(app.exec())

if __name__ == "__main__":
   main()